# Googleログインの設定
spring.security.oauth2.client.registration.google.client-id=411338896546-gp3g5qfhnvm84qm7ohp49bk2lbgc939a.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email,https://www.googleapis.com/auth/calendar.readonly
# トンネル（プロキシ）経由のアクセスを正しく処理する魔法の呪文
server.forward-headers-strategy=framework

server.port=${PORT:10000}